### ISSUE TITLE
SCA folder download failed

### ISSUE THREAD

**Issue by lxd666** [cc-dawg/nso#1]
Hello！
  Thank you very much for your work and code. 
  The download of the SCA folder failed, causing the program to run an error.
  Is it convenient to upload again, or where can I download it?

**Comment by ChristophRaab** [comment]
Hello! 
I am very sorry for the late reply. I haven't received any notification of the issue. 

The SCA folder is a little bit strange. I recommitted the originally intended files to the folder and you should be able to download them properly. 

Best
Christoph
